---
apiVersion: batch/v1
kind: Job
metadata:
  name: jingra-eval
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
      containers:
        - name: jingra
          image: docker.elastic.co/employees/sachinfrayne/jingra:$JINGRA_TAG
          imagePullPolicy: IfNotPresent
          workingDir: /app
          args: ["--config", "/config/jingra.yaml", "--evaluate-retrieval"]
          envFrom:
            - secretRef:
                name: jingra-es-credentials
            - secretRef:
                name: jingra-dataset-urls
            - secretRef:
                name: jingra-results-cluster
                optional: true
          env:
            - name: JINGRA_VERSION
              value: "$JINGRA_TAG"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-cluster-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: config
              mountPath: /config
            - name: results
              mountPath: /app/results
          resources:
            requests:
              memory: "10Gi"
              cpu: "3"
            limits:
              memory: "10Gi"
              cpu: "3"
      volumes:
        - name: config
          configMap:
            name: jingra-config
        - name: results
          emptyDir: {}
