apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
spec:
  version: 9.1.3
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: 3
      podTemplate:
        spec:
          nodeSelector:
            eks.amazonaws.com/nodegroup: elasticsearch-nodes
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 58Gi
                  cpu: 14
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: gp3
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 300Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: es-cluster
spec:
  version: 9.1.3
  http:
    service:
      spec:
        type: ClusterIP
  podTemplate:
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: kibana-node
  count: 1
  elasticsearchRef:
    name: es-cluster
  config:
    xpack.security.session.idleTimeout: "14d"
    xpack.security.session.lifespan: "1Y"
